### ISSUE TITLE
Add kakao login API 

### ISSUE THREAD

**Issue by seungjikim** [HangAround/HangAround-Front#5]
## 카카오 로그인 API 구현
* server 구현 및 명세 확인
* 유저 입장 테스트

**Comment by seungjikim** [comment]
@2214yj 예지야 혹시 명세는 어떤 거 보면 될까?? 그냥 코드 보고 하면되나해서

**Comment by iamRecoder** [comment]
승지야 지금 봤다...;_;
image.png
동작 로직 관련해서 명세서를 좀 더 자세하게 채워봤어..!

https://inpa.tistory.com/entry/NODE-%F0%9F%93%9A-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-Passport-%EA%B5%AC%ED%98%84
위의 블로그를 많이 참고했는데 블로그 글 끝부분에 카카오 로그인 인증 전략 처리 과정 완전 자세하게 써져 있어!!  명세서 설명이 빈약해서 위 블로그의 그 부분만 읽어봐도 훨씬 도움 될 거 같아!!

**Comment by iamRecoder** [comment]
@seungjikim 저 위에 image.png는 노션에 있는 API 명세서 캡쳐한 이미지 였어!

**Comment by iamRecoder** [comment]
승지야 지금 봤다...;_;
[image: image.png]
동작 로직 관련해서 명세서를 좀 더 자세하게 채워봤어..!

https://inpa.tistory.com/entry/NODE-%F0%9F%93%9A-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-Passport-%EA%B5%AC%ED%98%84
위의 블로그를 많이 참고했는데 블로그 글 끝부분에 카카오 로그인 인증 전략 처리 과정 완전 자세하게 써져 있어!!  명세서 설명이
빈약해서 위 블로그의 그 부분만 읽어봐도 훨씬 도움 될 거 같아!!
답장 늦어서 먄....


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
22.
03. 20. 오전 04:12:47

2022년 3월 20일 (일) 오전 2:29, seungjikim ***@***.***>님이 작성:
